name: C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: install gcc 8++
      run: sudo apt-get install -y gcc-8

    - name: checkout
      uses: actions/checkout@v2
    - name: run cmake
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER='gcc-8' -DCMAKE_BUILD_TYPE=Debug ..
    - name: ls PWD
      run: ls && $PWD
    - name: build 
      cmake --build . && ls
    - name: test
      run: cd build && ./unit_test
